/**
 * Franchise timelines, essential pre-watch roadmaps, and event countdown dates.
 */

export const FRANCHISE_TIMELINES = [
  {
    id: 'mcu-doomsday',
    title: 'Road to Avengers: Doomsday',
    shortTitle: 'MCU: Doomsday Prep',
    universe: 'Marvel Cinematic Universe',
    tagline: 'The essential Multiverse & Doom roadmap before the battle of the multiverse.',
    targetDate: '2026-05-01T00:00:00Z',
    targetEventTitle: 'Avengers: Doomsday In Theaters',
    backdropPath: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    trailerKey: 'eOrNdBpGMv8',
    trailerTitle: 'Avengers: Doomsday — Official Special Look & Cast Announcement',
    themeColor: '#ED1D24',
    phases: [
      { id: 'all', label: 'All Chronological Titles (15)' },
      { id: 'mutant', label: 'Mutant & Legacy Roots' },
      { id: 'avengers_foundation', label: 'Avengers Foundations' },
      { id: 'multiverse_incursions', label: 'Multiverse & Incursions' },
      { id: 'new_world', label: 'Phase 5 & 6 Escalation' },
    ],
    items: [
      {
        id: 36657,
        mediaId: 36657,
        mediaType: 'movie',
        title: 'X-Men',
        year: '2000',
        order: 1,
        tier: 'mutant',
        importance: 'LEGACY ORIGIN',
        importanceLabel: 'Mutant Genesis',
        description: 'The foundation of the mutant timeline and Wolverine\'s cinematic journey.',
        posterPath: '/bRDAc4GogS9yiRAEgAXeNu7mhr5.jpg',
      },
      {
        id: 36658,
        mediaId: 36658,
        mediaType: 'movie',
        title: 'X2: X-Men United',
        year: '2003',
        order: 2,
        tier: 'mutant',
        importance: 'EXPANDED',
        importanceLabel: 'Mutant Alliances',
        description: 'Mutants unite against William Stryker, laying deeper roots for the Fox-Marvel universe.',
        posterPath: '/4gctzZ1q9E3l6aK197kU1tC2C9p.jpg',
      },
      {
        id: 1771,
        mediaId: 1771,
        mediaType: 'movie',
        title: 'Captain America: The First Avenger',
        year: '2011',
        order: 3,
        tier: 'avengers_foundation',
        importance: 'FOUNDATION',
        importanceLabel: 'The First Hero',
        description: 'Steve Rogers becomes the super soldier and faces Red Skull and Hydra during WWII.',
        posterPath: '/vSNxAJTlD0r02V9sPYpqjqDAnsN.jpg',
      },
      {
        id: 24428,
        mediaId: 24428,
        mediaType: 'movie',
        title: 'The Avengers',
        year: '2012',
        order: 4,
        tier: 'avengers_foundation',
        importance: 'FOUNDATION',
        importanceLabel: 'Heroes Assemble',
        description: 'Earth\'s Mightiest Heroes form to stop Loki and the Chitauri invasion in New York.',
        posterPath: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
      },
      {
        id: 299536,
        mediaId: 299536,
        mediaType: 'movie',
        title: 'Avengers: Infinity War',
        year: '2018',
        order: 5,
        tier: 'avengers_foundation',
        importance: 'CRITICAL',
        importanceLabel: 'Universal Threat',
        description: 'Thanos collects the Infinity Stones, leading to the devastating cosmic Snap.',
        posterPath: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
      },
      {
        id: 299534,
        mediaId: 299534,
        mediaType: 'movie',
        title: 'Avengers: Endgame',
        year: '2019',
        order: 6,
        tier: 'avengers_foundation',
        importance: 'CRITICAL',
        importanceLabel: 'The Sacrifice',
        description: 'The Time Heist restores the universe and caps the Infinity Saga sacrifice.',
        posterPath: '/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
      },
      {
        id: 84958,
        mediaId: 84958,
        mediaType: 'tv',
        title: 'Loki (Season 1 & 2)',
        year: '2021-2023',
        order: 7,
        tier: 'multiverse_incursions',
        importance: 'CRITICAL',
        importanceLabel: 'Multiverse Throne',
        description: 'The Sacred Timeline collapses, introducing the TVA, branching timelines, and the God of Stories.',
        posterPath: '/voHUmluzYCL59W0wgik979umRt6.jpg',
      },
      {
        id: 566525,
        mediaId: 566525,
        mediaType: 'movie',
        title: 'Shang-Chi and the Legend of the Ten Rings',
        year: '2021',
        order: 8,
        tier: 'multiverse_incursions',
        importance: 'EXPANDED',
        importanceLabel: 'Cosmic Artifacts',
        description: 'Introduces ancient mystical artifacts transmitting a mysterious beacon across dimensions.',
        posterPath: '/1BIoJGKbXjdFDAvUEiA2VHqkK1Z.jpg',
      },
      {
        id: 634649,
        mediaId: 634649,
        mediaType: 'movie',
        title: 'Spider-Man: No Way Home',
        year: '2021',
        order: 9,
        tier: 'multiverse_incursions',
        importance: 'CRITICAL',
        importanceLabel: 'Multiverse Fracture',
        description: 'Spellcraft tears open the multiverse, bringing alternate universe heroes and villains together.',
        posterPath: '/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
        trailerKey: 'P3uI5sLosKU',
      },
      {
        id: 505642,
        mediaId: 505642,
        mediaType: 'movie',
        title: 'Black Panther: Wakanda Forever',
        year: '2022',
        order: 10,
        tier: 'new_world',
        importance: 'EXPANDED',
        importanceLabel: 'Global Vibranium Race',
        description: 'The clash of kingdoms between Wakanda and Talokan reshaping geopolitical power on Earth.',
        posterPath: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
      },
      {
        id: 823464,
        mediaId: 823464,
        mediaType: 'movie',
        title: 'Captain America: Brave New World',
        year: '2025',
        order: 11,
        tier: 'new_world',
        importance: 'EXPANDED',
        importanceLabel: 'Adamantium & Red Hulk',
        description: 'Sam Wilson takes flight amidst international conspiracies and the emergence of Adamantium.',
        posterPath: '/pzIddUEMWhWzfvLI3TwxUG2wGoi.jpg',
      },
      {
        id: 533535,
        mediaId: 533535,
        mediaType: 'movie',
        title: 'Deadpool & Wolverine',
        year: '2024',
        order: 12,
        tier: 'multiverse_incursions',
        importance: 'CRITICAL',
        importanceLabel: 'Anchor Beings & The Void',
        description: 'The Fox Marvel and MCU timeline merge, revealing Anchor Beings and the fate of doomed universes.',
        posterPath: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
      },
      {
        id: 453395,
        mediaId: 453395,
        mediaType: 'movie',
        title: 'Doctor Strange in the Multiverse of Madness',
        year: '2022',
        order: 13,
        tier: 'multiverse_incursions',
        importance: 'CRITICAL',
        importanceLabel: 'Incursions Collision',
        description: 'Dreamwalking and Darkhold magic cause universe-colliding Incursions across realities.',
        posterPath: '/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg',
      },
      {
        id: 986056,
        mediaId: 986056,
        mediaType: 'movie',
        title: 'Thunderbolts*',
        year: '2025',
        order: 14,
        tier: 'new_world',
        importance: 'EXPANDED',
        importanceLabel: 'Anti-Hero Coalition',
        description: 'Earth\'s covert anti-hero operative unit steps into the void left by the original Avengers.',
        posterPath: '/kKGQzkD4mE09P8gqJ5hT071uY1b.jpg',
      },
      {
        id: 617126,
        mediaId: 617126,
        mediaType: 'movie',
        title: 'The Fantastic Four: First Steps',
        year: '2025',
        order: 15,
        tier: 'new_world',
        importance: 'CRITICAL',
        importanceLabel: 'Doctor Doom Genesis',
        description: 'Marvel\'s First Family emerges from a retro-futuristic alternate universe, unlocking Victor Von Doom.',
        posterPath: '/5qBtcFkG28RjXG8pW7W0oN6yVj4.jpg',
      },
      {
        id: 1003596,
        mediaId: 1003596,
        mediaType: 'movie',
        title: 'Avengers: Doomsday',
        year: '2026',
        order: 16,
        tier: 'new_world',
        importance: 'DESTINATION',
        importanceLabel: 'The Main Event',
        description: 'The Multiverse collides under Doctor Doom (Robert Downey Jr.). Directed by the Russo Brothers.',
        posterPath: '/muth40792RuqEk05w8P28k3GZKG.jpg',
      },
    ],
  },
];

